# Generated by Django 4.2.30 on 2026-09-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamentos', '0002_solicitacaoinstalacao_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='computador',
            options={'ordering': ['laboratorio__nome', 'identificador']},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['categoria', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoinstalacao',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoinstalacao',
            name='atendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoinstalacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['computador', 'status', 'data_hora_inicio'], name='agendamento_computa_16cbf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(check=models.Q(('data_hora_fim__gt', models.F('data_hora_inicio'))), name='agendamento_fim_depois_do_inicio'),
        ),
        migrations.AddConstraint(
            model_name='computador',
            constraint=models.UniqueConstraint(fields=('laboratorio', 'identificador'), name='computador_identificador_unico_por_lab'),
        ),
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(fields=('nome', 'versao'), name='software_nome_versao_unico'),
        ),
    ]
