# Generated by Django 4.2.30 on 2026-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
