# Generated by Django 4.2.30 on 2026-09-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0.0, help_text='Tarifa por hora de uso', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.PositiveIntegerField(default=0, help_text='Capacidade máxima de pessoas/computadores')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versao', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('DEV', 'Desenvolvimento'), ('BD', 'Banco de Dados'), ('UTIL', 'Utilitários'), ('JOGOS', 'Jogos / Lazer')], default='DEV', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_nome', models.CharField(help_text='Nome e versão do software desejado', max_length=150)),
                ('justificativa', models.TextField(help_text='Motivo ou finalidade do uso')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_instalacao', to='agendamentos.computador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_instalacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALUNO', 'Aluno / Comunidade'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador')], default='ALUNO', max_length=10)),
                ('aprovado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='computador',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computadores', to='agendamentos.laboratorio'),
        ),
        migrations.AddField(
            model_name='computador',
            name='softwares',
            field=models.ManyToManyField(blank=True, related_name='computadores', to='agendamentos.software'),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20)),
                ('finalidade', models.CharField(choices=[('ESTUDO', 'Estudo / Pesquisa'), ('PROGRAMACAO', 'Desenvolvimento / Programação'), ('ADMINISTRATIVO', 'Atividades Administrativas'), ('JOGOS', 'Jogos / Eventos')], default='PROGRAMACAO', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamentos.computador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
