# Generated by Django 4.2.30 on 2026-09-09 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoinstalacao',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_instalacao', to='agendamentos.laboratorio'),
        ),
        migrations.AlterField(
            model_name='solicitacaoinstalacao',
            name='computador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_instalacao', to='agendamentos.computador'),
        ),
    ]
