# Generated by Django 4.2.30 on 2026-10-05 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamentos', '0003_alter_agendamento_options_alter_computador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor_hora_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa por hora vigente no momento da reserva (auditoria)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='computador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agendamentos.computador'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='computador',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computadores', to='agendamentos.laboratorio'),
        ),
    ]
