# Generated by Django 4.2.30 on 2026-10-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_protect_historico_e_tarifa_aplicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoinstalacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Retirado pelo solicitante')], default='PENDENTE', max_length=20),
        ),
    ]
