# Generated by Django 4.2.30 on 2026-10-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_solicitacao_status_cancelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('modo', models.CharField(choices=[('MAQUINA', 'Tarifa da máquina × multiplicador'), ('FIXO', 'Valor fixo por hora'), ('GRATUITO', 'Gratuito')], default='MAQUINA', max_length=10)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, help_text="Usado no modo 'Valor fixo por hora'", max_digits=6, null=True)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=1, help_text="Usado no modo 'Tarifa da máquina'. 1,00 = tarifa normal; 0,50 = 50% de desconto; 1,50 = acréscimo de 50%", max_digits=5)),
                ('duracao_maxima_min', models.PositiveIntegerField(blank=True, help_text='Duração máxima em minutos. Em branco = limite padrão do sistema', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Tipos inativos não aparecem para novas reservas')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de agendamento',
                'verbose_name_plural': 'Tipos de agendamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='finalidade',
            field=models.CharField(default='PROGRAMACAO', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agendamentos.tipoagendamento'),
        ),
    ]
