# Generated by Django 4.2.30 on 2026-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_tipos_com_valor_proprio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='valor_hora',
        ),
        migrations.RemoveField(
            model_name='tipoagendamento',
            name='multiplicador',
        ),
        migrations.AlterField(
            model_name='tipoagendamento',
            name='modo',
            field=models.CharField(choices=[('FIXO', 'Valor por hora'), ('GRATUITO', 'Gratuito')], default='FIXO', max_length=10),
        ),
        migrations.AlterField(
            model_name='tipoagendamento',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa cobrada por hora de uso (ignorada no modo gratuito)', max_digits=6, null=True),
        ),
    ]
